services:
  app:
    build:
      context: "."
      target: app-local
    volumes:
      - ./:/app

  web:
    build:
      context: "."
      target: web-local
    labels:
      traefik.enable: true
      traefik.docker.network: phpcon-dev
      traefik.http.routers.phpcon.entrypoints: websecure
      traefik.http.routers.phpcon.rule: Host(`template.phpcon-dev.pl`)
      traefik.http.routers.phpcon.tls: true
    networks:
      default: ~
      phpcon-dev: ~
    volumes:
      - ./public/:/app/public
    depends_on:
      app:
        condition: service_started

networks:
  phpcon-dev:
    external: true
